Hw1
Stranger488/tp_advcpp_homework pull request #1
Opened 2020-03-19 09:13 UTC by Stranger488

2020-03-20 13:33 UTC, smirnov-vs commented
дифф выглядит не полным, убедись, что все верно и маякни

2020-03-20 14:00 UTC, Stranger488 commented
> дифф выглядит не полным, убедись, что все верно и маякни

вроде бы все должно быть на месте

2020-03-20 14:19 UTC, smirnov-vs requested changes
Код в целом хороший, шлифуем до конца

2020-03-20 14:19 UTC, smirnov-vs commented on main.cpp
> -}
смущают эти штуки в МР, на будущее надо без них

2020-03-20 14:19 UTC, smirnov-vs commented on hw1/src/process.cpp
> +        std::cerr << "Process is not readable." << std::endl;
думаю пользователь будет удивлен, что библиотека пишет за него в stderr

2020-03-20 14:19 UTC, smirnov-vs commented on hw1/src/process.cpp
> +    ::close(proc_in);
этот метод закрывает stdin дочернему процессу
закрывать его stdout это уже архитектурно неверно
мы тут управляем только своей стороной, процесс своей

2020-03-20 14:19 UTC, smirnov-vs commented on hw1/src/process.cpp
> +void Process::close() {
этот метод закрывает процесс

2020-03-20 14:19 UTC, smirnov-vs commented on hw1/src/process.cpp
> +        exit(EXIT_SUCCESS);
недостижимый код

2020-03-20 14:19 UTC, smirnov-vs commented on hw1/src/main.cpp
> +            std::vector<char> big_buf(big_string.size());
лучше читать в строку тоже, для единообразия

2020-03-20 14:19 UTC, smirnov-vs commented on hw1/src/main.cpp
> +            std::string big_string(1e5, 'a');
тут просят целочисленное, лучше и писать целочисленное

2020-03-20 14:19 UTC, smirnov-vs commented on hw1/src/process.cpp
> +            throw std::runtime_error(std::strerror(errno));
потом не поймешь, кто именно отвалился

2020-03-20 14:21 UTC, Stranger488 commented on main.cpp
> -}
Да, хорошо, просто в мастере сначала порядок не навел, после слияния сделаю его таким, какой он должен быть

2020-03-20 14:25 UTC, Stranger488 commented on hw1/src/process.cpp
> +        std::cerr << "Process is not readable." << std::endl;
тогда можно просто возвращать 0? Или лучше исключение кинуть?

2020-03-20 14:28 UTC, Stranger488 commented on hw1/src/process.cpp
> +    ::close(proc_in);
хорошо

2020-03-20 14:29 UTC, smirnov-vs commented on hw1/src/process.cpp
> +        std::cerr << "Process is not readable." << std::endl;
вообще тут лучше исключение
в конкретном случае вообще это лишняя ответственность для этого метода, пусть этим программист занимается, интерфейс для него есть

2020-03-20 14:30 UTC, Stranger488 commented on hw1/src/process.cpp
> +void Process::close() {
понял

2020-03-20 14:30 UTC, Stranger488 commented on hw1/src/process.cpp
> +        exit(EXIT_SUCCESS);
+

2020-03-20 14:48 UTC, Stranger488 commented on hw1/src/main.cpp
> +            std::vector<char> big_buf(big_string.size());
хорошо

2020-03-20 14:48 UTC, Stranger488 commented on hw1/src/main.cpp
> +            std::string big_string(1e5, 'a');
хорошо

2020-03-20 14:49 UTC, Stranger488 commented on hw1/src/process.cpp
> +            throw std::runtime_error(std::strerror(errno));
+

2020-03-20 15:02 UTC, Stranger488 commented on hw1/src/process.cpp
> +        std::cerr << "Process is not readable." << std::endl;
хорошо, брошу исключение тогда здесь

2020-03-20 15:05 UTC, Stranger488 commented
поисправлял

2020-03-23 21:33 UTC, smirnov-vs requested changes

2020-03-23 21:33 UTC, smirnov-vs commented on hw1/src/main.cpp
> +        const size_t N = 1e5; // big_string size
проще написать 10000

2020-03-23 21:33 UTC, smirnov-vs commented on hw1/src/process.cpp
> +    kill(proc_pid, SIGTERM);
не подождал процесс

2020-03-23 21:33 UTC, smirnov-vs commented on hw1/src/process.cpp
> +        throw std::runtime_error(std::strerror(errno));
тут у тебя пайпы утекли

2020-03-23 21:33 UTC, smirnov-vs commented on hw1/src/main.cpp
> +            std::vector<char> buf(temp_string.size());
говорили вроде про строку

2020-03-23 21:44 UTC, Stranger488 commented on hw1/src/main.cpp
> +        const size_t N = 1e5; // big_string size
понял

2020-03-23 21:48 UTC, Stranger488 commented on hw1/src/process.cpp
> +    kill(proc_pid, SIGTERM);
+

2020-03-23 21:49 UTC, Stranger488 commented on hw1/src/process.cpp
> +        throw std::runtime_error(std::strerror(errno));
о, упустил, понял

2020-03-23 21:52 UTC, Stranger488 commented on hw1/src/main.cpp
> +            std::vector<char> buf(temp_string.size());
о, подумал, что это только ко второму случаю относилось, но здесь тоже ведь можно,
хорошо

2020-03-23 22:35 UTC, smirnov-vs commented on hw1/src/process.cpp
> +            throw std::runtime_error(std::strerror(errno));
пайпы утекли)

2020-03-23 23:10 UTC, Stranger488 commented on hw1/src/process.cpp
> +            throw std::runtime_error(std::strerror(errno));
затупил, понял

2020-03-25 21:46 UTC, smirnov-vs commented on hw1/src/process.cpp
> +        ::close(child_out);
такой код конечно полная беда без использования RAII, будем исправлять на красоту или так оставим?

2020-03-25 21:50 UTC, Stranger488 commented on hw1/src/process.cpp
> +        ::close(child_out);
Это придется сишные пайпы оборачивать в свой класс?

2020-03-25 21:51 UTC, smirnov-vs commented on hw1/src/process.cpp
> +        ::close(child_out);
возможно только дескриптор, возможно придется потом еще в пайп, как по ситуации пойдет

2020-03-25 21:52 UTC, Stranger488 commented on hw1/src/process.cpp
> +        ::close(child_out);
Или даже сишный файловый дескриптор нужно обернуть?

2020-03-25 21:54 UTC, Stranger488 commented on hw1/src/process.cpp
> +        ::close(child_out);
О, инет провис, попытаюсь конечно же

2020-03-26 01:18 UTC, Stranger488 commented on hw1/src/process.cpp
> +        ::close(child_out);
Попытался сделать, но без move и rvalue

2020-03-28 12:22 UTC, smirnov-vs commented on hw1/src/process.cpp
> +    close();
что-то утекает

2020-03-28 12:36 UTC, Stranger488 commented on hw1/src/process.cpp
> +    close();
а, ну да, ведь я забрал и stdout у пайпа, но не закрыл в его в close у Process'a, добавил в метод close() закрытие еще stdout'a.

2020-03-28 13:33 UTC, smirnov-vs approved these changes

2020-03-28 13:33 UTC, merged