Hw2
Stranger488/tp_advcpp_homework pull request #2
Opened 2020-03-26 22:46 UTC by Stranger488

2020-03-30 10:57 UTC, a-badin requested changes

2020-03-30 10:57 UTC, a-badin commented on hw2/include/BaseLogger.hpp
> +    explicit BaseLogger(const Level lvl);
А зачем тут const, lvl это же копия

2020-03-30 10:57 UTC, a-badin commented on hw2/include/BaseLogger.hpp
> +    void set_level(const Level lvl);
Опять не понял зачем const

2020-03-30 10:57 UTC, a-badin commented on hw2/include/BaseLogger.hpp
> +    const Level level();
Тут тоже не понятно зачем const, поставьте лучше const после скобок

2020-03-30 10:57 UTC, a-badin commented on hw2/include/BaseLogger.hpp
> +#include <unordered_map>
map для объявления не нужен, поэтому лучше его удалить

2020-03-30 10:57 UTC, a-badin commented on hw2/include/FileLogger.hpp
> +    std::ofstream file_out;
нижний дэш

2020-03-30 10:57 UTC, a-badin commented on hw2/include/FileLogger.hpp
> +    explicit FileLogger(const std::string& file, const Level lvl);
explicit нужен только если параметр 1

2020-03-30 10:57 UTC, a-badin commented on hw2/include/Global.hpp
> +#include <getopt.h>
лишний

2020-03-30 10:57 UTC, a-badin commented on hw2/src/Global.cpp
> +    Logger::get_instance().set_global_logger(std::make_unique<FileLogger>(path, lvl));
Имелось ввиду просто вернуть этот указатель из функции.
create_file_logger

2020-03-30 10:57 UTC, a-badin commented on hw2/include/Logger.hpp
> +    void set_global_logger(std::unique_ptr<BaseLogger>&& logger);
Принимайте по значению, эффект будет точно такой же

2020-03-30 10:57 UTC, a-badin commented on hw2/include/Logger.hpp
> +    std::unique_ptr<BaseLogger>& get_global_logger();
Посмотрите начало лекции 3, Если вам нужно дать данные на пользование, но не отдавать владение - передавайте по ссылке или указателю.

2020-03-30 10:57 UTC, a-badin commented on hw2/include/LogInitializer.hpp
> +    explicit LogInitializer(int argc, char* argv[]);
лишний explicit

2020-03-30 10:57 UTC, a-badin commented on hw2/include/LogInitializer.hpp
> +    LogOutput out;
дэши в приватный членах класса

2020-03-30 10:57 UTC, a-badin commented on hw2/include/LogOutputModifier.hpp
> +const std::unordered_map<const Level, const LogColorCode> LEVEL_COLOR {
Оба мэпа не используются в объявлении и относятся к реализации.
Нужно вынести в LogOutputModifier.cpp как static или в анонимном пространстве имен

2020-03-30 10:57 UTC, a-badin commented on hw2/include/LogOutputModifier.hpp
> +enum LogColorCode {
И его тоже, почему не enum class ?

2020-03-30 10:57 UTC, a-badin commented on hw2/include/LogOutputModifier.hpp
> +    FG_RED = 31,
FG_ не нужен будет если объявить как enum class

2020-03-30 10:57 UTC, a-badin commented on hw2/include/LogOutputModifier.hpp
> +    LogColorCode code;
дэши на приватный члены класса

2020-03-30 10:57 UTC, a-badin commented on hw2/include/LogOutputModifier.hpp
> +    bool is_colored;
Тут хватает bool'а, но есть момент. Если вы сделаете под colored enum c читаемыми значениями, у вас вместо несовсем понятного вызова LogOutputModifier(lvl, false), где чтобы понять что делает false, нужно открывать объявение метода,  будет весьма понятный LogOutputModifier(lvl, Color::UNCOLORED). Плюс если у вас добавится еще состоний, например, Color::AUTO вам будет проще его добавить

2020-03-30 10:57 UTC, a-badin commented on hw2/src/LogOutputModifier.cpp
> +    if (!mod.is_colored) {
Кажется наоборот, если is_colored - то выводим цвет

2020-03-30 10:57 UTC, a-badin commented on hw2/include/LogOutputModifier.hpp
> +#define LOG_STRING_DEBUG "DEBUG"
1998 давно закончился.
```
namespace {
constexpr std::string LOG_STRING_DEBUG = "DEBUG";
} // namespace
```
А вообще вы можете сразу инициализировать мапу строковыми значениями, они у вас нигде больше не используются

2020-03-30 10:57 UTC, a-badin commented on hw2/CMakeLists.txt
> +        src/StderrLogger.cpp src/StdoutLogger.cpp src/LogOutputModifier.cpp src/LogInitializer.cpp)
Я бы поспорил, нужен ли LogInitializer в самой библиотеке.

2020-03-30 16:31 UTC, Stranger488 commented on hw2/include/BaseLogger.hpp
> +    explicit BaseLogger(const Level lvl);
понял

2020-03-30 16:37 UTC, Stranger488 commented on hw2/include/BaseLogger.hpp
> +    void set_level(const Level lvl);
убрал

2020-03-30 16:37 UTC, Stranger488 commented on hw2/include/BaseLogger.hpp
> +    const Level level();
понял

2020-03-30 16:38 UTC, Stranger488 commented on hw2/include/BaseLogger.hpp
> +#include <unordered_map>
точно, удалил

2020-03-30 16:42 UTC, Stranger488 commented on hw2/include/FileLogger.hpp
> +    std::ofstream file_out;
хорошо

2020-03-30 16:49 UTC, Stranger488 commented on hw2/include/FileLogger.hpp
> +    explicit FileLogger(const std::string& file, const Level lvl);
хорошо, понял

2020-03-30 16:50 UTC, Stranger488 commented on hw2/include/Global.hpp
> +#include <getopt.h>
точно, убрал

2020-03-30 17:02 UTC, Stranger488 commented on hw2/src/Global.cpp
> +    Logger::get_instance().set_global_logger(std::make_unique<FileLogger>(path, lvl));
понял, хорошо

2020-03-30 17:14 UTC, Stranger488 commented on hw2/include/LogInitializer.hpp
> +    explicit LogInitializer(int argc, char* argv[]);
понял

2020-03-30 17:14 UTC, Stranger488 commented on hw2/include/LogInitializer.hpp
> +    LogOutput out;
понял

2020-03-30 17:22 UTC, Stranger488 commented on hw2/include/LogOutputModifier.hpp
> +const std::unordered_map<const Level, const LogColorCode> LEVEL_COLOR {
понял, вынес в как static

2020-03-30 17:26 UTC, Stranger488 commented on hw2/include/LogOutputModifier.hpp
> +enum LogColorCode {
были проблема с тем, чтобы писать напрямую LogColorCode::COLOR в ostream, теперь, чтобы не перегружать enum class LogColorCode, сделаю static_cast<int>(LogColorCode::COLOR). 
Это нормально, делать такой каст? Или лучше тогда перегрузку делать?

2020-03-30 17:28 UTC, Stranger488 commented on hw2/include/LogOutputModifier.hpp
> +enum LogColorCode {
И он же нужен в объявлении, там поле класса использует тип LogColorCode

2020-03-30 17:30 UTC, Stranger488 commented on hw2/include/LogOutputModifier.hpp
> +    FG_RED = 31,
окей, но тот же вопрос выше сохраняется с enum class'ом

2020-03-30 17:30 UTC, Stranger488 commented on hw2/include/LogOutputModifier.hpp
> +    LogColorCode code;
окей

2020-03-30 17:31 UTC, Stranger488 commented on hw2/include/LogOutputModifier.hpp
> +    bool is_colored;
окей, понял

2020-03-30 17:34 UTC, Stranger488 commented on hw2/src/LogOutputModifier.cpp
> +    if (!mod.is_colored) {
поменял bool на enum class

2020-03-30 17:35 UTC, Stranger488 commented on hw2/include/LogOutputModifier.hpp
> +#define LOG_STRING_DEBUG "DEBUG"
понял, тогда лучше сразу строками инициализирую

2020-03-30 17:46 UTC, Stranger488 commented on hw2/CMakeLists.txt
> +        src/StderrLogger.cpp src/StdoutLogger.cpp src/LogOutputModifier.cpp src/LogInitializer.cpp)
окей, то есть выходит, что работа с аргументами командной строки для библиотеки дополнительный функционал, который в нее саму лучше не включать? Тогда из namespace'a тоже уберу

2020-03-30 18:01 UTC, Stranger488 commented on hw2/include/Logger.hpp
> +    void set_global_logger(std::unique_ptr<BaseLogger>&& logger);
понял

2020-03-30 18:16 UTC, Stranger488 commented on hw2/include/Logger.hpp
> +    std::unique_ptr<BaseLogger>& get_global_logger();
а в этом случае под данными не подразумевается сам указатель? 

То есть я так понимаю, если бы там нужен был std::string, то нужно было бы вернуть ссылку на него, а тут из-за полиморфизма нужен именно указатель - ну он и возвращается как ссылка

2020-04-04 08:15 UTC, a-badin commented on hw2/include/Logger.hpp
> +    std::unique_ptr<BaseLogger>& get_global_logger();
Нет, под данными понимается сам логгер, вы же вызываете его как get_global_logger()->debug(msg); Вам не важно как хранится logger, вам главное получить доступ к его методам.
Ссылки тоже сохраняют полиморфиз. Спрашивайте меня в чате - я тогда отвечу сразу

2020-04-04 08:28 UTC, a-badin commented on hw2/CMakeLists.txt
> +        src/StderrLogger.cpp src/StdoutLogger.cpp src/LogOutputModifier.cpp src/LogInitializer.cpp)
Ну я бы сказал, это такой ну очень редкий сценарий. Клиент вполне может занять аргументы vqwfe своей логикой. Клиент может захотеть сделать конфигурацию лога ввиде файла.

2020-04-04 08:35 UTC, a-badin requested changes

2020-04-04 08:35 UTC, a-badin commented on hw2/src/StdoutLogger.cpp
> +        std::cout << LogOutputModifier(lvl, LogColorState::COLORED) << msg << std::endl;
Наверное надо вернуть после вывода цвет обратно в белый, а то все что после - тоже раскрашивается

2020-04-04 14:12 UTC, Stranger488 commented on hw2/src/StdoutLogger.cpp
> +        std::cout << LogOutputModifier(lvl, LogColorState::COLORED) << msg << std::endl;
Точно, сделал

2020-04-04 14:20 UTC, Stranger488 commented on hw2/include/Logger.hpp
> +    std::unique_ptr<BaseLogger>& get_global_logger();
Точно, понял, спасибо

2020-04-04 14:24 UTC, Stranger488 commented on hw2/CMakeLists.txt
> +        src/StderrLogger.cpp src/StdoutLogger.cpp src/LogOutputModifier.cpp src/LogInitializer.cpp)
Хорошо, понял

2020-04-07 10:48 UTC, a-badin approved these changes

2020-04-07 10:48 UTC, a-badin commented on hw2/src/Logger.cpp
> +    global_logger_ = std::move(logger);
Если я передам пустой unique_ptr то все поломается

2020-04-07 10:50 UTC, merged

2020-04-07 13:58 UTC, Stranger488 commented on hw2/src/Logger.cpp
> +    global_logger_ = std::move(logger);
Оой, добавил проверку на null