Hw3
Stranger488/tp_advcpp_homework pull request #3
Opened 2020-04-02 19:14 UTC by Stranger488

2020-04-05 14:20 UTC, smirnov-vs requested changes

2020-04-05 14:20 UTC, smirnov-vs commented on hw3/src/client.cpp
> +        Tcp::Connection connection(std::string(argv[1]), std::stoi(argv[2]));
explicit конвертирование не обязательно

2020-04-05 14:20 UTC, smirnov-vs commented on hw3/tcp/src/Server.cpp
> +        throw std::runtime_error(std::strerror(errno));
есть утечка

2020-04-05 14:20 UTC, smirnov-vs commented on hw3/tcp/include/Server.hpp
> +    void set_max_connect(int max_connect);
для размеров size_t

2020-04-07 16:12 UTC, Stranger488 commented on hw3/src/client.cpp
> +        Tcp::Connection connection(std::string(argv[1]), std::stoi(argv[2]));
+

2020-04-07 16:12 UTC, Stranger488 commented on hw3/tcp/src/Server.cpp
> +        throw std::runtime_error(std::strerror(errno));
аа, точно, дескриптор из accept'a утечет, исправил - закрыл

2020-04-07 16:12 UTC, Stranger488 commented on hw3/tcp/include/Server.hpp
> +    void set_max_connect(int max_connect);
о, точно, понял

2020-04-08 22:45 UTC, smirnov-vs approved these changes
пора сделать RAII обертку для дескриптора и не мучиться в след дз

2020-04-09 17:54 UTC, Stranger488 commented
> пора сделать RAII обертку для дескриптора и не мучиться в след дз

в следующем обязательно сделаю
здесь подумал, что можно без нее обойтись, но, видимо, зря

2020-04-11 00:22 UTC, merged