Hw4
Stranger488/tp_advcpp_homework pull request #4
Opened 2020-04-11 00:24 UTC by Stranger488

2020-04-14 23:08 UTC, smirnov-vs approved these changes
Обсудим детали на РК

2020-04-17 15:39 UTC, smirnov-vs requested changes

2020-04-17 15:39 UTC, smirnov-vs commented on hw4/src/server.cpp
> +            server.init(argv[1], std::stoi(argv[2]), read_from_client_handler, write_to_client_handler);
оформить, чтобы понимать смысл

2020-04-17 15:39 UTC, smirnov-vs commented on hw4/tcp_epoll/src/Server.cpp
> +    res = bind(fd_, reinterpret_cast<sockaddr*>(&addr), sizeof(addr));
рассказать про bind

2020-04-17 15:39 UTC, smirnov-vs commented on hw4/tcp_epoll/src/Server.cpp
> +            throw std::runtime_error(std::strerror(errno));
утечка

2020-04-17 15:49 UTC, Stranger488 commented on hw4/src/server.cpp
> +            server.init(argv[1], std::stoi(argv[2]), read_from_client_handler, write_to_client_handler);
+

2020-04-17 16:00 UTC, Stranger488 commented on hw4/tcp_epoll/src/Server.cpp
> +    res = bind(fd_, reinterpret_cast<sockaddr*>(&addr), sizeof(addr));
bind позволяет как бы дать имя сокету (то есть привязать адрес addr к сокету с файловым дескриптором fd_ в данном случае)

2020-04-17 16:00 UTC, Stranger488 commented on hw4/tcp_epoll/src/Server.cpp
> +            throw std::runtime_error(std::strerror(errno));
+

2020-04-19 16:43 UTC, smirnov-vs approved these changes
после лекции можем закрыть это дз

2020-04-27 18:03 UTC, merged