Hw5
Stranger488/tp_advcpp_homework pull request #5
Opened 2020-04-17 22:32 UTC by Stranger488

2020-04-22 11:41 UTC, a-badin requested changes
Ваша реализация работает только пока строки маленькие, это называется small object optimization, когда маленький буфер кладется в память сразу после самого объекта, поэтому ваши строки попадают в общую память. Напишите мне если будут сложности

2020-04-22 11:41 UTC, a-badin commented on hw5/shmem/include/ShMemAlloc.hpp
> +struct AllocState {
А что у этого типа меняется в зависимости от T?

2020-04-22 11:41 UTC, a-badin commented on hw5/shmem/include/ShMemAlloc.hpp
> +    ShMemAlloc(const ShMemAlloc<U>& other) {
Верхнее копирование поидее покрывается этим

2020-04-22 11:41 UTC, a-badin commented on hw5/shmem/include/ShMemAlloc.hpp
> +        alloc_ = reinterpret_cast<AllocState<value_type>*>(other.alloc_);
Добавили аргумент в AllocState,  себе и спасибо за все

2020-04-22 11:41 UTC, a-badin commented on hw5/shmem/include/ShMemAlloc.hpp
> +    return left == right;
На самом деле тут все немного хитрее. По документации true only if the storage allocated by the allocator a1 can be deallocated through a2. В случае когда у вас эти ShMemAlloc принаджлежат двум разным mmap, они не могут деалоцировать память друг друга. Вам нужно проверять, что они принадлежат одному mmap

2020-04-22 11:41 UTC, a-badin commented on hw5/shmem/include/Map.hpp
> +        mmap_ptr_ = make_shmem<value_type>(mmap_number);
На самом деле странно, вы выделяете указатель под  std::pair<const Key, T> а храните там  AllocState и семафор, я бы выделил просто char*

2020-04-22 11:41 UTC, a-badin commented on hw5/shmem/include/Semaphore.hpp
> +    Semaphore(sem_t* ptr) {
Странно передавать аргументом адрес памяти, храните тут sem_t по значению и создавайте весь класс в map через  placement new - это ровно то что вам нужно, создать объект по адресу в памяти

2020-04-22 11:41 UTC, a-badin commented on hw5/shmem/include/Map.hpp
> +    T& at(const Key& key) {
На самом деле возвращать ссылку не имеет смысла, так как это race condition

2020-04-22 11:41 UTC, a-badin commented on hw5/src/main.cpp
> +    shmem::Map< int, std::basic_string<char, std::char_traits<char>> > map(MMAP_NUMBER);
а чем не нравится std::string?

2020-04-22 11:41 UTC, a-badin commented on hw5/src/main.cpp
> +        map.insert({1, "one"});
Не будет работать если строка будет длинее ~20 символов

2020-04-24 12:25 UTC, Stranger488 commented on hw5/shmem/include/ShMemAlloc.hpp
> +    ShMemAlloc(const ShMemAlloc<U>& other) {
Иначе не компилится даже
Смотрел некоторые реализации аллокаторов, и в них всегда этот конструктор обязательным был
Ну и на cppreference в конструкторах аллокаторов есть такой как минимум
Я не совсем до конца смог понять, для чего он используется, но судя по ошибке, которую выдает компилятор, если убрать такой конструктор (```no matching function for call to «shmem::ShMemAlloc<std::_Rb_tree_node<std::pair<const int, std::__cxx11::basic_string<char> > > >::ShMemAlloc(const allocator_type&)```),  у аллокатора std::map'a просто должен быть такой конструктор, только не совсем ясно, конечно, что внутри все же точно должно быть

2020-04-24 12:33 UTC, Stranger488 commented on hw5/shmem/include/ShMemAlloc.hpp
> +    return left == right;
А это можно проверить через указатель на alloc_ в аллокаторе? Если этот указатель в одном аллокаторе совпадает с указателем в другом аллокаторе, то они должны принадлежать одному mmap

2020-04-24 12:37 UTC, Stranger488 commented on hw5/shmem/include/ShMemAlloc.hpp
> +struct AllocState {
Изначально менялось, забыл убрать
убрал

2020-04-24 12:46 UTC, Stranger488 commented on hw5/shmem/include/Map.hpp
> +        mmap_ptr_ = make_shmem<value_type>(mmap_number);
Но это же указатель, через который мы получаем доступ к памяти, выделенной посредством mmap, и там хранятся и AllocState и семафор и std::map или я неправильно рассуждаю?

2020-04-24 13:18 UTC, Stranger488 commented on hw5/shmem/include/Semaphore.hpp
> +    Semaphore(sem_t* ptr) {
А член класса Semaphore, через который будут вызываться методы sem_init, sem_wait... будет валидным? Ну то есть если брать адрес этого члена и передавать этим методам, то разве корректно будет?

2020-04-24 13:22 UTC, Stranger488 commented on hw5/shmem/include/Map.hpp
> +    T& at(const Key& key) {
А средства синхронизации вроде семафоров не нужные для того, чтобы избежать race condition? 
Или тут если где-то сохранить ссылку, то можно через нее попытаться модифицировать объект в мапе сразу из двух процессов?

2020-04-24 13:22 UTC, Stranger488 commented on hw5/src/main.cpp
> +    shmem::Map< int, std::basic_string<char, std::char_traits<char>> > map(MMAP_NUMBER);
+

2020-04-24 14:54 UTC, Stranger488 commented on hw5/shmem/include/ShMemAlloc.hpp
> +    ShMemAlloc(const ShMemAlloc<U>& other) {
+

2020-04-24 14:54 UTC, Stranger488 commented on hw5/shmem/include/ShMemAlloc.hpp
> +        alloc_ = reinterpret_cast<AllocState<value_type>*>(other.alloc_);
+

2020-04-24 14:55 UTC, Stranger488 commented on hw5/shmem/include/ShMemAlloc.hpp
> +    return left == right;
+

2020-04-24 14:55 UTC, Stranger488 commented on hw5/shmem/include/Map.hpp
> +        mmap_ptr_ = make_shmem<value_type>(mmap_number);
+

2020-04-24 14:55 UTC, Stranger488 commented on hw5/shmem/include/Semaphore.hpp
> +    Semaphore(sem_t* ptr) {
+

2020-04-24 14:55 UTC, Stranger488 commented on hw5/shmem/include/Map.hpp
> +    T& at(const Key& key) {
+

2020-04-30 15:59 UTC, a-badin approved these changes

2020-04-30 15:59 UTC, a-badin commented on hw5/shmem/include/ShMemAlloc.hpp
> +        alloc_->start += sizeof(value_type) * n;
вот тут только нужно сначала запомнить место старта, чтобы потом его вернуть, а потом только сдвигать

2020-04-30 16:02 UTC, a-badin approved these changes
По-моему, получилось здорово.
Кода мало, потопить кажется что невозможно, классы маленькие и отвечают каждый за что-то своё. Правьте конфликт и заливайте.

Шестая домашняя работа засчитана на 7

2020-05-01 16:31 UTC, Stranger488 commented on hw5/shmem/include/ShMemAlloc.hpp
> +        alloc_->start += sizeof(value_type) * n;
+

2020-05-01 16:39 UTC, merged